---
- name: create useful groups
  become: yes
  become_user: root
  group: name={{item}} state=present
  with_items:
    - docker
    - wheel
    - admin
    - dev
    - vboxusers
    - sudo
    - ada
    - libvirt
    - blade
    - qemu
    - kvm
